DROPRATE_OPENING = "Opening";
DROPRATE_SKINNING = "Skinning";
DROPRATE_MINING = "Mining";
DROPRATE_HERB_GATHERING = "Herb Gathering";
DROPRATE_GOLD = "Gold";
DROPRATE_SILVER = "Silver";
DROPRATE_COPPER = "Copper";
DROPRATE_RECEIVES = "receives";
